version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-bookstore
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gozero
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - /e/dockerData/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis-bookstore
    ports:
      - "6379:6379"
    volumes:
      - /e/dockerData/redis:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  default:
    name: bookstore-network
